//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Scripts/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Installation"",
            ""id"": ""d019e108-ca48-4a49-93f6-cedc5774d460"",
            ""actions"": [
                {
                    ""name"": ""DevShiftIndex"",
                    ""type"": ""Value"",
                    ""id"": ""3b6d9ca9-e407-4028-91f8-3cf426f42ad6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""33bf5d4d-1228-43cc-973f-6b3eccc11e2e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ffd7931-ce17-48ea-8243-ba61280244c2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4d7f6c8e-7a40-4e3e-b488-c33ea95aa125"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""6e0b893c-52d2-45b9-b223-467f4d140cfd"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3d572385-d6ff-4a69-a12b-a76fc58d021d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""36ab207b-b7a3-46b4-a2a9-62b1af8f239d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""24966e7c-7bcb-4f81-acaa-7eb5f35d9aab"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""dacf1a94-c492-47fd-a3e0-c7151071f7d5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dab7b820-2014-4165-b537-7f58772fe378"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""49236601-5b12-49ab-a2c8-5bd779ba5ff0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DevShiftIndex"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Installation
        m_Installation = asset.FindActionMap("Installation", throwIfNotFound: true);
        m_Installation_DevShiftIndex = m_Installation.FindAction("DevShiftIndex", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Installation
    private readonly InputActionMap m_Installation;
    private List<IInstallationActions> m_InstallationActionsCallbackInterfaces = new List<IInstallationActions>();
    private readonly InputAction m_Installation_DevShiftIndex;
    public struct InstallationActions
    {
        private @PlayerInput m_Wrapper;
        public InstallationActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @DevShiftIndex => m_Wrapper.m_Installation_DevShiftIndex;
        public InputActionMap Get() { return m_Wrapper.m_Installation; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InstallationActions set) { return set.Get(); }
        public void AddCallbacks(IInstallationActions instance)
        {
            if (instance == null || m_Wrapper.m_InstallationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InstallationActionsCallbackInterfaces.Add(instance);
            @DevShiftIndex.started += instance.OnDevShiftIndex;
            @DevShiftIndex.performed += instance.OnDevShiftIndex;
            @DevShiftIndex.canceled += instance.OnDevShiftIndex;
        }

        private void UnregisterCallbacks(IInstallationActions instance)
        {
            @DevShiftIndex.started -= instance.OnDevShiftIndex;
            @DevShiftIndex.performed -= instance.OnDevShiftIndex;
            @DevShiftIndex.canceled -= instance.OnDevShiftIndex;
        }

        public void RemoveCallbacks(IInstallationActions instance)
        {
            if (m_Wrapper.m_InstallationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInstallationActions instance)
        {
            foreach (var item in m_Wrapper.m_InstallationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InstallationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InstallationActions @Installation => new InstallationActions(this);
    public interface IInstallationActions
    {
        void OnDevShiftIndex(InputAction.CallbackContext context);
    }
}
